### PR TITLE
fix: use new ssbc name

### PR DESCRIPTION
**Pull request by decentral1se**
Unsure what this will break :grimacing: 

Motivation: https://github.com/ssbc/go-ssb/issues/160

### CODE REVIEW

**Comment by staltz** [comment]
@decentral1se I almost missed this PR because I wasn't GH-watching this repo (now I am). If you need something merged, try to ping a couple maintainers.

**Review by staltz — CHANGES_REQUESTED** [review]
Tests were passing on the main branch, so it's important to keep them passing. Can you update [tfk/encoding.go](https://github.com/ssbc/go-ssb-refs/pull/2/files#diff-8cf93f3d24a1dcae695a5fa47b81ba32857c73e8b57eb3d523bb2fcbaed99d4e)?

**Comment by decentral1se** [comment]
@staltz thanks for the review, missed the test suite but seems fixed now!

```
go test -v ./...
=== RUN   TestParseRef
    refs_test.go:80: 9 <@ye+Q.ed25519>
    refs_test.go:80: 10 <@ye+Q.gabbygrove-v1>
    refs_test.go:80: 11 <&84SS.sha256>
    refs_test.go:80: 12 <%2jDr.sha256>
    refs_test.go:80: 13 <%vof0.cloaked>
    refs_test.go:80: 14 <%2jDr.gabbygrove-v1>
--- PASS: TestParseRef (0.00s)
=== RUN   TestAnyRef
--- PASS: TestAnyRef (0.00s)
=== RUN   TestParseBranches
--- PASS: TestParseBranches (0.00s)
=== RUN   TestBranchSequential
--- PASS: TestBranchSequential (0.00s)
=== RUN   TestBranchConcurrent
--- PASS: TestBranchConcurrent (0.00s)
=== RUN   TestBranchMerge
    tangles_sort_test.go:126: 0 p1 0
    tangles_sort_test.go:126: 1 a1 2
    tangles_sort_test.go:126: 2 b1 2
    tangles_sort_test.go:126: 3 p2 3
--- PASS: TestBranchMerge (0.00s)
=== RUN   TestBranchMergeOpen
--- PASS: TestBranchMergeOpen (0.00s)
=== RUN   TestBranchMergeOpenTwo
--- PASS: TestBranchMergeOpenTwo (0.00s)
=== RUN   TestBranchMergeMulti
--- PASS: TestBranchMergeMulti (0.00s)
=== RUN   TestBranchHelperHops
--- PASS: TestBranchHelperHops (0.00s)
=== RUN   TestParseSimpleURIs
=== RUN   TestParseSimpleURIs/canon_message_(ssb_v1)
=== RUN   TestParseSimpleURIs/canon_message_(bendy)
=== RUN   TestParseSimpleURIs/canon_feed_(classic)
=== RUN   TestParseSimpleURIs/canon_feed_(bendy_butt)
=== RUN   TestParseSimpleURIs/canon_blob
--- PASS: TestParseSimpleURIs (0.00s)
    --- PASS: TestParseSimpleURIs/canon_message_(ssb_v1) (0.00s)
    --- PASS: TestParseSimpleURIs/canon_message_(bendy) (0.00s)
    --- PASS: TestParseSimpleURIs/canon_feed_(classic) (0.00s)
    --- PASS: TestParseSimpleURIs/canon_feed_(bendy_butt) (0.00s)
    --- PASS: TestParseSimpleURIs/canon_blob (0.00s)
=== RUN   ExampleNewExperimentalURI
--- PASS: ExampleNewExperimentalURI (0.00s)
PASS
ok  	github.com/ssbc/go-ssb-refs	(cached)
=== RUN   TestFormatFeedRef
=== RUN   TestFormatFeedRef/ed25519
=== RUN   TestFormatFeedRef/gabby
=== RUN   TestFormatFeedRef/bamboo
=== RUN   TestFormatFeedRef/metafeed
=== RUN   TestFormatFeedRef/tooShort
=== RUN   TestFormatFeedRef/unknown-algo
--- PASS: TestFormatFeedRef (0.00s)
    --- PASS: TestFormatFeedRef/ed25519 (0.00s)
    --- PASS: TestFormatFeedRef/gabby (0.00s)
    --- PASS: TestFormatFeedRef/bamboo (0.00s)
    --- PASS: TestFormatFeedRef/metafeed (0.00s)
    --- PASS: TestFormatFeedRef/tooShort (0.00s)
    --- PASS: TestFormatFeedRef/unknown-algo (0.00s)
=== RUN   TestFormatMessageRef
=== RUN   TestFormatMessageRef/sha256
=== RUN   TestFormatMessageRef/gabby
=== RUN   TestFormatMessageRef/bamboo
=== RUN   TestFormatMessageRef/metafeed
=== RUN   TestFormatMessageRef/tooShort
=== RUN   TestFormatMessageRef/unknown-algo
--- PASS: TestFormatMessageRef (0.00s)
    --- PASS: TestFormatMessageRef/sha256 (0.00s)
    --- PASS: TestFormatMessageRef/gabby (0.00s)
    --- PASS: TestFormatMessageRef/bamboo (0.00s)
    --- PASS: TestFormatMessageRef/metafeed (0.00s)
    --- PASS: TestFormatMessageRef/tooShort (0.00s)
    --- PASS: TestFormatMessageRef/unknown-algo (0.00s)
PASS
ok  	github.com/ssbc/go-ssb-refs/tfk	(cached)
```

**Comment by staltz** [comment]
Thanks for the PR!

**Pull request merged**
